Test invoice payment chargerback reservals
killbill/killbill-integration-tests pull request #19
Opened 2018-03-13 20:42 UTC by wwjfrodriguez

I submit this PR for review in that specific endpoint because I need help to understand better how chargerback reservals works. I don't write assertions yet in the test because I'm always recieve a BadRequest:

` KillBillClient::API::BadRequest: {"className":"com.fasterxml.jackson.databind.JsonMappingException","code":null,"message":"Can not instantiate value of type [simple type, class org.killbill.billing.jaxrs.json.InvoicePaymentTransactionJson] from String value ('KillBillClient::Model::InvoicePayment'); no single-String constructor/factory method\n at [Source: org.apache.catalina.connector.CoyoteInputStream@7f233e5; line: 1, column: 1]","causeClassName":null,"causeMessage":null,"stackTrace":[]}
`

Or:

`KillBillClient::API::BadRequest: {"className":"java.lang.IllegalArgumentException","code":null,"message":"transactionExternalKey amount needs to be set","causeClassName":null,"causeMessage":null,"stackTrace":[]}`

2018-03-14 06:29 UTC, pierre commented
I'm guessing these errors come from the fact that the API client isn't correctly implemented, see https://github.com/killbill/killbill-client-ruby/pull/47#discussion_r174361478.

Take a look at this message for instance:

```
KillBillClient::API::BadRequest: {"className":"java.lang.IllegalArgumentException","code":null,"message":"transactionExternalKey amount needs to be set","causeClassName":null,"causeMessage":null,"stackTrace":[]}
```

This message (which has a typo in it unfortunately) comes from: https://github.com/killbill/killbill/blob/6b092a0ca5d812ac6acab938b2b874b59c9abcf9/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoicePaymentResource.java#L251

Some background on chargeback reversals can be found in this ticket: https://github.com/killbill/killbill/issues/477. Here is a test that can provide guidance on how these work: https://github.com/killbill/killbill/blob/6b092a0ca5d812ac6acab938b2b874b59c9abcf9/payment/src/test/java/org/killbill/billing/payment/api/TestPaymentApi.java#L1207.

Basically, the flow is:

1. Create payment (e.g. `PURCHASE`)
2. Trigger chargeback
3. Trigger chargeback reversal

2018-03-14 20:53 UTC, wwjfrodriguez reviewed
@pierre please verify this.

2018-03-14 20:53 UTC, wwjfrodriguez commented on killbill-integration-tests/core/test_invoice_payment.rb
> +    def test_create_chargeback_and_chargeback_reversal
@pierre please verify this.

2018-03-15 09:21 UTC, pierre requested changes
Logic looks good, let's just make a few more assumptions around the account balance.

This is to make sure the right endpoints are called (if we were to call the pure payment APIs instead of the invoice payment APIs, the account balance wouldn't be updated).

2018-03-15 09:21 UTC, pierre commented on killbill-integration-tests/core/test_account.rb
> -    def test_emails_notifications
⚠️ It looks like the conflict resolution led to this being deleted.

Might be easier to cherry-pick the good commit (https://git-scm.com/docs/git-cherry-pick) or rebase it (https://git-scm.com/book/en/v2/Git-Branching-Rebasing) on top of a clean branch.

2018-03-15 09:21 UTC, pierre commented on killbill-integration-tests/core/test_invoice_payment.rb
> +      assert_equal('CHARGEBACK', account_transactions[1].transaction_type)
Can you also verify the status is `SUCCESS`?

2018-03-15 09:21 UTC, pierre commented on killbill-integration-tests/core/test_invoice_payment.rb
> +      assert_equal('CHARGEBACK', account_transactions[2].transaction_type)
Can you also verify the status is `PAYMENT_FAILURE`?

2018-03-15 09:21 UTC, pierre commented on killbill-integration-tests/core/test_invoice_payment.rb
> +
Can you check the account balance here?

```
assert_equal(0, get_account(@account.account_id, true, true, @options).account_balance)
```

2018-03-15 09:21 UTC, pierre commented on killbill-integration-tests/core/test_invoice_payment.rb
> +
Can you check the account balance here?

```
assert_equal(50, get_account(@account.account_id, true, true, @options).account_balance)
```

2018-03-15 09:21 UTC, pierre commented on killbill-integration-tests/core/test_invoice_payment.rb
Can you check the account balance here?

```
assert_equal(0, get_account(@account.account_id, true, true, @options).account_balance)
```

2018-03-15 14:37 UTC, wwjfrodriguez commented
@pierre I already implemented all your requested changes, please verify.

2018-03-15 15:26 UTC, pierre approved these changes

2018-03-15 15:26 UTC, merged